-- run this script to ingest: php tools/import_sql.php python_scripts/sql/ingest_skills_pages_31_37.sql
BEGIN TRANSACTION;

INSERT OR IGNORE INTO skills (name) VALUES
-- Agriculture / Forestry / Fishery
('Evisceration Processor'),
('Genomicist'),
('Internet of Things'),
('Climate-smart Practices'),
('Automation'),
('Chatbots'),
('Drones'),
('Blockchains'),
('Nanotechnology'),
('Food Sharing and Crowd Farming'),
('Green Technology and Green Practices'),
('Diagnostic Ability'),
('Promotion of Products'),
('Use of Mobile Applications'),

-- Construction
('Nano/Microsatellites'),
('3D Drafter'),
('BIM Modeler'),
('BIM Specialist'),
('BIM Manager'),
('BIM Team Leader'),
('Skills for AAC (Autoclaved Aerated Concrete)'),
('Smart / Green Construction Installation (Solar, Wind)'),
('Skills for Engineering Services Outsourcing (ESO)'),
('Skills for Glass Fiber Reinforced Concrete (GFRC)'),
('Process Automation Specialists'),
('Robotics Specialist and Engineer'),
('Rubberized Asphalt (Asphalting)'),
('Skills for Sea-based Construction'),
('Fiber Optic Cable (Underwater) Installation'),
('Tunnelling (Subway Construction)'),
('Energy Labelling'),
('Reuse and Recycling of Construction and Demolition Waste'),

-- Health and Wellness
('Health and Wellness Coaching'),
('Lifestyle Medicine'),
('Data Analysts and Scientists'),
('Biologists and Geneticists'),
('AI and Machine Learning Specialists'),
('Information Technology Services'),
('Environmental and Occupational Health and Hygiene Professionals'),
('Big Data Specialists'),
('Administrative and Executive Secretaries'),
('Supply Chain and Logistics Specialists'),
('Specialist Medical Practitioners'),
('Use of Electronic Medical Records'),
('Occupational Safety and Health'),
('Basic Sanitation'),
('Ethical Standards'),
('Professionalism'),
('Customer Relations'),
('Preventive or Curative Medical Knowledge'),
('Standard of Care'),

-- Information and Communication Technology (ICT)
('Super Agents (Multi-taskers)'),
('Automation and Artificial Intelligence'),
('Application Development Management (ADM)'),
('System Integration'),
('Automation Enablement'),
('IoT Enablement Languages'),
('Preventive Health'),
('Remote Healthcare Management'),
('3D Animation'),
('Augmented and Virtual Reality (AR/VR)'),
('Gamification'),
('Knowledge Process Outsourcing'),
('Big Data and Analytics'),
('Internet of Things'),
('Engineering Services Outsourcing'),
('Performance Management'),
('Legal Process Outsourcing'),
('Provider Services'),
('Industry-specific Services (Telecom, Healthcare, Insurance, Pharmaceutical)'),
('Behavioral Health Professionals'),
('Genetic Counselling Professionals'),
('Machine Learning'),
('Sales Services'),
('Robotics'),
('IT-related Skills'),
('Emotional Intelligence'),
('Programming Skills'),
('People Management'),
('Complex Problem Solving'),
('Cloud Computing'),
('STEM Skills'),
('English Proficiency'),
('Creativity'),
('Leadership Skills'),
('Emotional Quotient (EQ)'),
('Basic Math'),
('Communication Skills'),
('Comprehension'),
('Analytical Skills'),
('Critical Thinking'),
('Logical Thinking'),
('Ethical Practice'),
('Computer Literacy'),
('Hardware Servicing'),
('Typing'),
('Multitasking Skills'),
('Advanced Coding'),
('Entrepreneurial Skills'),
('Customer Service'),
('Time Management'),
('Independence'),
('Self-motivation'),
('Results-oriented'),
('Collaboration'),
('Reliability'),
('Positive Attitude'),

-- Manufacturing
('Compliance to Standards and Certifications'),
('Quality Control (Total and Statistical)'),
('Occupational Safety'),
('Leadership and People Supervision'),
('Shopfloor Math'),
('General and Operations Management'),
('Sales and Marketing'),
('Organisational Development'),
('Mechanical Engineering'),
('Research and Development'),
('New Technology Specialization'),
('Innovation Management'),
('Advanced Materials and Additive Manufacturing'),
('Artificial Intelligence'),
('Big Data'),
('Cybersecurity'),
('Industrial Internet of Things'),
('Modeling, Simulation, Visualization and Immersion'),
('Sensor Production'),
('Autonomous Vehicles Production'),
('3D Printing / Additive Manufacturing'),
('Smart Devices'),

-- Tourism
('Digital Marketing'),
('Eco-tourism'),
('Foreign Language Skills'),
('General and Operations Management'),
('User Experience and Human-Machine Interaction Design'),
('Software and Applications Development'),
('Product Management'),
('Information Security Analysis'),
('Brand and Communications'),
('IT Skills'),
('Management Skills'),
('Business Skills'),
('People Management'),
('Personal Skills'),
('Tourism Skills'),
('Communication and Language Skills'),
('Food Preparation and Hygiene'),
('Tourism Orientation'),
('Sustainable Tourism (Coastal Ecology and Habitat Protection)'),
('Team Work'),
('Workplace Health and Safety'),
('Computer Literacy'),

-- Transportation, Communication, Storage and Logistics
('E-Commerce and Social Media'),
('Process Automation'),
('Order Tracking and Coordination'),
('Transport Network Vehicle Service (TNVS)'),
('Vehicle Sharing Service'),
('Information Security Analysis'),
('Logistics Software'),
('Process Automation Specialist'),
('Software and Applications Development and Analysis'),
('Innovation Management'),
('Service and Solutions Design'),
('Product Management'),
('Industrial and Production Engineering'),
('Supply Chain and Logistics'),
('Communication Skills'),
('Computer Skills'),
('Math Skills'),
('Good Moral Character'),
('Integrity'),
('Core Soft Skills'),
('Initiative'),
('Dedication'),
('Work Ethics'),
('Determination'),
('Safety Skills'),
('Green Skills'),
('Management and Organization Skills');

COMMIT;
