-- run this script to ingest:
--   php tools/import_sql.php python_scripts/sql/ingest_job_titles.sql job_occupations

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS job_occupations (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL UNIQUE,
	embedding BLOB
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_job_occupations_title ON job_occupations(title);
CREATE INDEX IF NOT EXISTS idx_job_occupations_title ON job_occupations(title);

INSERT OR IGNORE INTO job_occupations (title) VALUES
-- Agriculture / Forestry / Fishery
('Machine Operation'),
('Tractor / Hand Tractor Operator'),
('Tillers Operator'),
('Harvester Operator'),
('Mechanical Dryers Operator'),
('Threshers Operator'),
('Milling Equipment Operator'),
('Small Engine Mechanic for Fishing Boats with Fiberglass Hulls'),
('Fish and Marine Products Processor'),
('Fish Feeder'),
('Food Processor'),
('Heavy Equipment Mechanic'),
('Horticultural Worker'),
('Packer'),
('Piggery Worker / Technician'),
('Plant Pathologist'),
('Poultry Producer'),
('Seaweed Farmer'),
('Slaughterer'),
('Farmer / Farm Worker / Livestock and Poultry Raiser'),
('Fisherman / Aquaculture Farmer / Aquaculture Farm Caretaker / Aide'),

-- Automotive / Land Transportation / Manufacturing
('Machine Operator'),
('Dump Truck Loader'),

-- Construction
('Bricklayer and Related Worker'),
('Cabinet-maker'),
('Laborer / Helper'),
('Construction Painter'),
('Pipe Fitter'),
('Road Grader and Scraper Operator'),
('Landscape Artist'),
('Rigger'),
('Tile Setter'),
('Mobile Crane Operator'),
('Scaffolder'),
('Pipefitter'),
('Carpenter'),
('Heavy Equipment Operator'),
('Hydraulic Excavator Operator'),
('Rebar Worker'),
('Hydraulic Equipment Operator'),
('Electrician'),
('Plumber'),
('Excavator Operator'),
('Steel Man'),
('Draftsman'),
('Mixer Operator'),
('Bulldozer Operator'),
('Paver Operator'),
('Crane Operator (Including Mobile Cranes)'),
('Bookkeeper'),
('Driver'),
('Mason'),
('Scaffold Erector'),
('Welder'),

-- Health and Wellness
('Community Health Worker'),
('Customer Service Representative'),
('Massage Therapist'),
('Pharmacy Aide'),
('Agri-crops Production Worker (Natural Health Products Industry)'),
('Emergency Medical Technician'),
('Optician'),
('Front-liners’ Skills Worker'),
('Dental Equipment Laboratory Technician'),
('Dental Assistant'),
('Caregiver'),
('Nursing Aide'),
('Pharmacy Assistant'),

-- Information and Communication Technology (ICT)
('CAD / CAM Operator'),
('Call Center Agent (Voice and Non-Voice)'),
('Customer Service Representative / Specialist'),
('Software Developer'),
('Technical Support'),
('Web Developer'),
('Computer Transcriptionist'),
('IT Specialist / Staff'),
('Graphic Artist (Including Video Graphic Artist)'),
('Programmer'),
('Game Developer'),
('IT Developer'),
('Animator / 3D Animator'),
('Gamification Specialist'),
('Medical Claims Representative'),
('Medical Claims Specialist'),
('Medical Claims Manager'),
('Medical Claims Service Delivery Manager'),
('Medical Coder'),
('Software Development Specialist'),
('Sales Services Specialist'),
('Client Servicing Specialist'),
('Animation Artistry Specialist'),
('Computer Systems Service Personnel / Technician'),
('IT Support Specialist'),
('IT Technician'),
('Content Developer'),

-- Manufacturing
('Metal Fabrication – Tool and Die'),
('Food Production – Food Processor'),
('Food Production – Dairy Processor'),
('Food Production – Cake Decorator'),
('Food Production – Livestock Feeds Producer'),
('Electronics Manufacturing – Automotive Electronics'),
('Electronics Manufacturing – Semiconductor Production'),
-- Manufacturing / Automotive / Chemical / Electronics
('Automotive Manufacturing – Automotive Parts Production / Assembly of Motor Vehicles'),
('Chemical Production – Plastics'),
('Garments Production – Tailoring'),
('Garments Production – Dressmaking'),
('Garments Sewer'),
('Paper Products Manufacturing – Mechatronics'),
('Metal Fabrication – Forklift Operations'),
('Metal Fabrication – Mechatronics'),
('Electronics Manufacturing – Mechatronics'),
('Chemical Production – Forklift Operation'),
('Chemical Production – Mechatronics'),
('Automotive Mechanic'),
('Automotive Painter'),
('Electronics Equipment Assembler'),
('Instrumentation and Calibration Technician'),
('Machine Mechanic'),
('Machine Operator and Assembler'),
('Metal Caster'),
('Molder (Metal Products)'),
('Motorcycle Technician'),
('Plant / Machine Operator and Assembler'),
('Smart Press Machine Operator'),
('Repairman'),
('Miner / Machine / Heavy Equipment Operator'),
('Specialized Sales Representative'),
('Master Mechanic'),

-- Food, Hospitality, and Tourism
('Food and Beverages Staff / Attendant / Handler'),
('Waiter'),
('Tourist Guide'),
('Cook'),
('Cuisine Chef'),
('Executive Chef'),
('Gourmet Chef'),
('Online Booking and Front Desk Officer (ICT-driven)'),
('Housekeeping Staff'),
('Barista'),
('Front Office Agent'),
('Food and Beverages Manager'),
('Food Technologist / Food Safety Expert'),
('Cake Decorator'),
('Event Coordinator'),
('Licensed Wine Expert'),
('Service Crew / Waiter / Food and Beverage Assistant'),
('Baker'),

-- Health, Personal Services, and Culture
('Cosmetic Dentist / Surgeon'),
('English / Korean / Chinese Proficient Front Desk Officer'),
('English / Korean / Chinese Proficient Customer Service Relations Officer'),
('Receptionist'),
('Port Staff'),
('Aquaculturist'),
('Horticulturist'),
('Magician'),

-- Administration, Transport, and Logistics
('Administrative Clerk'),
('Ticketing Issuing / Travel Clerk'),
('Ticket Teller'),
('Customer Service Representative / Associate'),
('Shipping Operations Officer'),
('Transport Network Vehicle Service (TNVS) Driver / Taxi Driver'),
('Terminal and Warehouse Personnel'),
('Bus Driver'),
('Truck Driver'),
('Machine Operator'),
('Forklift Operator'),
('Forklift Driver'),

-- Garments and Creative
('Tailor'),
('Dressmaker'),
('Animator'),

-- ICT / Creative / Media
('Web Developer'),
('Graphic Artist'),
('Programmer'),
('Game Developer'),
('IT Developer'),
('Back-up Singer'),
('Solo Singer'),
('Band Vocalist / Lead Singer'),
('Professional Photographer'),
('Comics Artist'),
('Book / Magazine Illustrator'),
('Cartoonist'),

-- Business and Sales
('Financial Assistant'),
('Sales Representative'),
('Sales Clerk');

COMMIT;